-- ============================================================
-- メールアカウント連携 Phase 1（受信＝読む）
--   共有メール（問い合わせ窓口）を IMAP で受信同期し、アプリ上で読む。
--   ・mail_accounts  … 連携アカウント（メタ情報。認証情報は含めない）
--   ・mail_messages  … 受信メール本体（自前DBキャッシュ）
--   ・mail_sync_state… アカウント別の同期状態（UIDVALIDITY / 最終同期UID）
--
--   ⚠️ IMAP のパスワードは DB に置かない。サーバー環境変数から取得する
--      （lib/email.ts の SMTP と同じ思想）。mail_accounts.auth_ref は
--      環境変数のキー接頭辞（例 "SUPPORT" → MAIL_SUPPORT_IMAP_*）を指す。
--   ⚠️ 個人情報（差出人・本文）を含むため RLS は運営（is_ops）のみ。
--      同期・書き込みは service_role（サーバー）で行う。
-- ============================================================

-- ── 連携アカウント ──────────────────────────────────────────
create table if not exists public.mail_accounts (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  address       text    not null,                       -- メールアドレス
  display_name  text    not null default '',            -- 表示名（用途ラベル）
  provider      text    not null default 'imap',         -- imap / gmail / graph（Phase 1 は imap）
  auth_ref      text    not null,                        -- 認証情報の参照（環境変数キー接頭辞）
  is_shared     boolean not null default true,           -- 共有窓口か個人か
  status        text    not null default 'connected',    -- connected / error / paused
  status_detail text    not null default '',             -- 直近エラーの内容など
  last_synced_at timestamptz,                            -- 最終同期時刻
  sort_order    int     not null default 0,
  is_deleted    boolean not null default false
);

create unique index if not exists mail_accounts_address_uq
  on public.mail_accounts(lower(address)) where is_deleted = false;

comment on table public.mail_accounts is
  'メール連携アカウント（メタ情報のみ）。IMAP資格情報は環境変数（auth_ref接頭辞）で管理。';

-- ── 受信メール本体（自前DBキャッシュ）──────────────────────
create table if not exists public.mail_messages (
  id           bigint generated by default as identity primary key,
  account_id   bigint  not null references public.mail_accounts(id) on delete cascade,
  uid          bigint  not null,                         -- IMAP UID（アカウント×UIDVALIDITYで一意）
  message_id   text    not null default '',              -- RFC Message-ID（重複排除・スレッド用）
  thread_key   text    not null default '',              -- スレッド束ね（正規化した件名など）
  from_name    text    not null default '',
  from_addr    text    not null default '',              -- 差出人（小文字正規化済み）
  to_addr      text    not null default '',
  subject      text    not null default '',
  snippet      text    not null default '',              -- 本文プレビュー（先頭抜粋）
  body_text    text    not null default '',
  body_html    text    not null default '',
  member_id    bigint  references public.members(id) on delete set null,  -- 会員照合の結果（null=未登録）
  is_read      boolean not null default false,
  is_starred   boolean not null default false,           -- 個人メモ（IMAP \Flagged と同期可）
  is_flagged   boolean not null default false,           -- 要対応（共有マーク・自前DB）
  has_attach   boolean not null default false,
  received_at  timestamptz,                              -- 受信日時（Envelope date）
  synced_at    timestamptz not null default now()
);

-- アカウント内で UID は一意（冪等な取り込み＝二重取り込み防止）
create unique index if not exists mail_messages_uid_uq
  on public.mail_messages(account_id, uid);
create index if not exists mail_messages_list_idx
  on public.mail_messages(account_id, received_at desc);
create index if not exists mail_messages_member_idx
  on public.mail_messages(account_id, member_id) where member_id is not null;
create index if not exists mail_messages_flag_idx
  on public.mail_messages(account_id, is_flagged) where is_flagged = true;
create index if not exists mail_messages_unread_idx
  on public.mail_messages(account_id, is_read) where is_read = false;

comment on table public.mail_messages is
  '受信メールのDBキャッシュ。member_id は会員照合結果（登録メアドフィルタの土台）。';

-- ── 同期状態 ────────────────────────────────────────────────
create table if not exists public.mail_sync_state (
  account_id     bigint primary key references public.mail_accounts(id) on delete cascade,
  uid_validity   bigint,                                 -- IMAPのUIDVALIDITY（変わったら全再取得）
  last_seen_uid  bigint not null default 0,              -- 取り込み済みの最大UID
  updated_at     timestamptz not null default now()
);

comment on table public.mail_sync_state is
  'アカウント別のIMAP同期カーソル。uid_validity 変化時は last_seen_uid をリセットする。';

-- ── RLS：運営（管理者・オペレーター）のみ閲覧可 ──────────────
--   is_ops() は migration_phase1_rls.sql で定義済み（security definer）。
--   書き込み（同期）は service_role で行うため RLS を通らない。
alter table public.mail_accounts   enable row level security;
alter table public.mail_messages   enable row level security;
alter table public.mail_sync_state enable row level security;

drop policy if exists "mail_accounts_ops" on public.mail_accounts;
create policy "mail_accounts_ops" on public.mail_accounts
  for all to authenticated
  using (public.is_ops()) with check (public.is_ops());

drop policy if exists "mail_messages_ops" on public.mail_messages;
create policy "mail_messages_ops" on public.mail_messages
  for all to authenticated
  using (public.is_ops()) with check (public.is_ops());

drop policy if exists "mail_sync_state_ops" on public.mail_sync_state;
create policy "mail_sync_state_ops" on public.mail_sync_state
  for all to authenticated
  using (public.is_ops()) with check (public.is_ops());
