-- ============================================================
-- リスト管理 Phase 5：操作監査ログ
--   確定事項 A4=a「エクスポートの実行を記録する」を満たすためのテーブル。
--
--   ⚠️ 既存の「対応ログ」(get_staff_activity) は line_messages / mail_send_log /
--      chat_messages / payments を横断 UNION する**読み取り専用ビュー**であり、
--      追記できるログテーブルではない。そこへ枝を足すと対応ログ画面
--      （種別フィルタ・集計・CSV）まで波及するため、本フェーズでは
--      リスト管理に閉じた専用テーブルを作る。
--      将来 get_staff_activity に合流させられるよう、列は
--      「いつ・誰が・何を・どれだけ」の形に揃えてある。
--
--   前提：migration_add_contact_lists.sql（Phase 1）適用済み。
-- ============================================================

create table if not exists public.contact_list_audit (
  id          bigint generated by default as identity primary key,
  -- リストを消しても記録は残す（誰が持ち出したかは残さなければ意味がない）
  list_id     bigint references public.contact_lists(id) on delete set null,
  action      text        not null
                check (action in ('export', 'merge', 'merge_source')),
  actor       uuid,                                   -- auth.users.id（取得できなければ null）
  actor_label text        not null default '',        -- 実施時点の表示名／メール（スナップショット）
  row_count   int         not null default 0,         -- 書き出した行数／移した件数
  detail      jsonb       not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists idx_contact_list_audit_list
  on public.contact_list_audit(list_id, id desc);
create index if not exists idx_contact_list_audit_at
  on public.contact_list_audit(created_at desc);

comment on table public.contact_list_audit is
  'リストへの操作履歴。エクスポート（個人情報の持ち出し）とマージを記録する。追記のみ。';
comment on column public.contact_list_audit.actor_label is
  '実施者の表示名・メール（実施時点のスナップショット。会員側を消しても誰がやったか残す）';
comment on column public.contact_list_audit.detail is
  '補足。export: {listName, scope, filter, fields} / merge: {destName, sourceIds, sourceNames, skipped}';

alter table public.contact_list_audit enable row level security;

-- 参照・追記とも運営のみ。
--   ⚠️ update / delete のポリシーは意図的に作らない（追記専用にするため）。
--      RLS 有効下でポリシーの無い操作は全て拒否される。
drop policy if exists "contact_list_audit_ops_select" on public.contact_list_audit;
create policy "contact_list_audit_ops_select" on public.contact_list_audit
  for select to authenticated
  using (public.is_ops());

drop policy if exists "contact_list_audit_ops_insert" on public.contact_list_audit;
create policy "contact_list_audit_ops_insert" on public.contact_list_audit
  for insert to authenticated
  with check (public.is_ops());

-- ロールバック（必要時のみ）
-- drop table if exists public.contact_list_audit;
