-- ============================================================
-- メール定型文テンプレート（P2）
--   メール作成モーダルから差し込む定型文。件名・本文をセットで保持。
--   読み書きはサーバー（service role）経由のみ（RLSは有効・ポリシー無し＝
--   クライアント直アクセスは拒否）。
-- ============================================================
create table if not exists public.mail_templates (
  id          bigint generated by default as identity primary key,
  name        text not null default '',
  subject     text not null default '',
  body        text not null default '',
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.mail_templates enable row level security;

comment on table public.mail_templates is
  'メール作成用の定型文テンプレート（件名＋本文）。サーバー経由でのみ読み書き。';
