-- ============================================================
-- リスト管理（配信先リスト）
--   メールアドレス・電話番号を「リスト」として登録・管理し、
--   一斉配信／シナリオ配信の配信先として使えるようにする。
--
--   contact_lists           … リスト枠（画面の左ペイン）
--   contact_list_imports    … 一括取込ジョブ（Phase 2 で使用。先に器だけ作る）
--   contact_list_entries    … レコード（画面の右ペイン）
--   contact_list_deliveries … 配信で使われた履歴（送信時点のスナップショット）
--
--   設計方針（preview/設計書/2026-08-17_リスト管理機能_設計書.html rev.2）
--     ・重複判定は「ファイル内」と「同一リスト内」のみ。他リストは照合しない
--     ・生の入力値（表示用）と正規化値（重複判定用）を別カラムで持つ
--     ・会員に依存しない独立エンティティ（member_id は nullable）
--     ・並び順は手動（sort_order を 10 刻みで採番）
--     ・削除はアーカイブ（論理削除）のみ。物理削除はしない
--
--   ⚠️ すべて運営専用（RLS = is_ops()）。会員クライアントからは触らせない。
--   ⚠️ 何度実行しても安全（if not exists）。
-- ============================================================

-- ── リスト枠 ────────────────────────────────────────────────
create table if not exists public.contact_lists (
  id               bigint generated by default as identity primary key,
  name             text        not null,
  description      text        not null default '',
  note1            text        not null default '',
  note2            text        not null default '',
  folder_id        bigint      references public.folders(id) on delete set null,
  -- 件数の非正規化キャッシュ。recount_contact_list() で冪等に復元できる
  entry_count      int         not null default 0,
  emailable_count  int         not null default 0,   -- メール送信できる件数
  phone_only_count int         not null default 0,   -- 電話のみ（メール配信不可）
  -- 手動並べ替え。10 刻みで採番し、挿入は前後の中間値を使う（昇順で表示）
  sort_order       int         not null default 0,
  allow_delivery   boolean     not null default true,  -- 配信先として選べるか
  consent_note     text        not null default '',    -- 取得元・同意メモ（特定電子メール法の記録用）
  is_archived      boolean     not null default false, -- アーカイブ（宛先に選べない／履歴は残る）
  is_deleted       boolean     not null default false, -- 論理削除（マスタ方針に合わせる）
  created_by       uuid,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- 既定の並び＝手動（sort_order）。同値は更新の新しい順で安定させる
create index if not exists idx_contact_lists_order
  on public.contact_lists(sort_order, updated_at desc) where is_deleted = false;

comment on table  public.contact_lists              is 'リスト枠（配信先リスト）。レコードは contact_list_entries';
comment on column public.contact_lists.sort_order   is '手動並べ替えの位置（10刻み）。昇順で表示。同値は updated_at desc';
comment on column public.contact_lists.is_archived  is 'アーカイブ。配信先には選べないが配信履歴の参照用に残す';
comment on column public.contact_lists.consent_note is '取得元・同意メモ。特定電子メール法の同意記録（リスト単位）';
comment on column public.contact_lists.entry_count  is '件数キャッシュ。recount_contact_list() で再集計できる';

-- ── 取込ジョブ（Phase 2 で使用。entries が参照するため先に作る）──────
create table if not exists public.contact_list_imports (
  id              bigint generated by default as identity primary key,
  list_id         bigint      not null references public.contact_lists(id) on delete cascade,
  file_name       text        not null default '',
  file_kind       text        not null default 'csv',    -- 'csv' | 'paste'（'md' は Phase 5）
  encoding        text        not null default 'utf-8',  -- 'utf-8' | 'utf-8-bom' | 'cp932'
  delimiter       text        not null default ',',
  column_map      jsonb       not null default '{}'::jsonb,
  dup_policy      text        not null default 'skip',   -- 'skip' | 'update' | 'abort'
  blank_overwrite boolean     not null default false,    -- 空欄で既存値を上書きするか（既定オフ）
  skip_suppressed boolean     not null default true,     -- 配信停止リストのアドレスを除外するか
  total_rows      int         not null default 0,
  inserted        int         not null default 0,
  updated         int         not null default 0,
  skipped         int         not null default 0,
  failed          int         not null default 0,
  error_rows      jsonb       not null default '[]'::jsonb, -- 失敗行CSVの生成元（30日で消す）
  status          text        not null default 'queued',   -- queued|running|done|failed|canceled
  error_message   text,
  created_by      uuid,
  started_at      timestamptz,
  finished_at     timestamptz,
  created_at      timestamptz not null default now()
);
create index if not exists idx_contact_imports_list
  on public.contact_list_imports(list_id, id desc);

comment on table  public.contact_list_imports            is 'リストの一括取込ジョブ。非同期実行の進捗と結果を保持';
comment on column public.contact_list_imports.error_rows is '失敗行（元の値＋失敗理由）。失敗CSVのダウンロード元。30日で消す';

-- ── レコード ────────────────────────────────────────────────
create table if not exists public.contact_list_entries (
  id          bigint generated by default as identity primary key,
  list_id     bigint      not null references public.contact_lists(id) on delete cascade,
  -- 会員（members）に紐づいたら入る。非会員の生アドレスは null のまま
  member_id   bigint      references public.members(id) on delete set null,
  matched_by  text,                                    -- 'member_id' | 'email' | null
  -- 生の入力値（表示用）と正規化値（重複判定用）を必ず分ける
  --   ⚠️ 正規化はアプリ側（lib/contactLists.ts）で行う。生成列にしない
  --      （Gmail 限定のドット除去ロジックを2箇所に分散させないため）
  email       text,
  email_norm  text,
  phone       text,
  phone_e164  text,
  name        text        not null default '',
  age_group   text,                                    -- '10代'…'80代以上' | '不明'
  prefecture  text,
  note1       text        not null default '',
  note2       text        not null default '',
  source_kind text        not null default 'manual',   -- 'manual' | 'csv'（'md'|'api' は将来）
  import_id   bigint      references public.contact_list_imports(id) on delete set null,
  consent_at  timestamptz,                             -- 同意日時（レコード単位・任意）
  consent_src text,                                    -- 同意の取得元
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  -- 要件：メールアドレス・電話番号のどちらか一方は必須
  --   ⚠️ 正規化後の列に掛ける。生 email だけ入って email_norm が null（＝形式不正）の
  --      レコードを作らせないため
  constraint entry_contact_required
    check (email_norm is not null or phone_e164 is not null)
);

-- 同一リスト内の重複防止（部分UNIQUE。scenario_entries_email_uk と同じ流儀）
create unique index if not exists contact_entries_email_uk
  on public.contact_list_entries (list_id, email_norm) where email_norm is not null;
create unique index if not exists contact_entries_phone_uk
  on public.contact_list_entries (list_id, phone_e164) where phone_e164 is not null;
-- 会員名寄せ・配信時の突合用
create index if not exists idx_contact_entries_email_norm on public.contact_list_entries(email_norm);
create index if not exists idx_contact_entries_member     on public.contact_list_entries(member_id);
-- keyset ページング用（OFFSET を使わない）
create index if not exists idx_contact_entries_list_id    on public.contact_list_entries(list_id, id desc);

comment on table  public.contact_list_entries             is 'リストのレコード（連絡先）。メール・電話のどちらか一方が必須';
comment on column public.contact_list_entries.email_norm  is '重複判定用の正規化メール。小文字化＋Gmail系のみドット/+タグ除去';
comment on column public.contact_list_entries.phone_e164  is '重複判定用の正規化電話（E.164）。既定国は日本（+81）';
comment on column public.contact_list_entries.member_id   is '会員と紐づいた場合の members.id。非会員は null';
comment on column public.contact_list_entries.matched_by  is '紐づけの根拠：member_id=ID一致 / email=正規化メールでの名寄せ';

-- ── 配信履歴（送信時点のスナップショット）────────────────────
create table if not exists public.contact_list_deliveries (
  id                 bigint generated by default as identity primary key,
  list_id            bigint      not null references public.contact_lists(id) on delete cascade,
  kind               text        not null,             -- 'broadcast' | 'scenario'
  broadcast_id       bigint      references public.broadcasts(id) on delete set null,
  scenario_id        bigint      references public.scenarios(id)  on delete set null,
  -- ↓ 後からリストや配信を編集・改名・削除しても履歴が壊れないための写し
  list_name_snapshot text        not null default '',
  title_snapshot     text        not null default '',
  channel            text        not null default 'email',
  target_count       int         not null default 0,    -- 送信時点のリスト件数
  sent_count         int         not null default 0,
  excluded_count     int         not null default 0,
  -- {suppressed:12, phone_only:24, invalid:2, dup:3}
  excluded_breakdown jsonb       not null default '{}'::jsonb,
  sent_at            timestamptz not null default now()
);
create index if not exists idx_contact_deliv_list
  on public.contact_list_deliveries(list_id, sent_at desc);

comment on table public.contact_list_deliveries is
  'リストを宛先に使った配信の履歴。件数・リスト名は送信時点のスナップショット';

-- ── 既存テーブルへの列追加（後方互換：すべて default 付き）──────
--   target_mode / audience_type は text のまま 'list' を受け付ける。
--   既存値（all / filter / email / member）の挙動は一切変えない。
alter table public.broadcasts
  add column if not exists target_list_ids bigint[] not null default '{}',
  add column if not exists list_dedupe     boolean  not null default true;
alter table public.scenarios
  add column if not exists target_list_ids bigint[] not null default '{}';

comment on column public.broadcasts.target_list_ids is
  'target_mode=list のときの配信先リスト（contact_lists.id）';
comment on column public.broadcasts.list_dedupe is
  '複数リストで重複するアドレスを1通にまとめるか（既定 true）';
comment on column public.scenarios.target_list_ids is
  'audience_type=list のときの配信先リスト（contact_lists.id）';

-- ============================================================
-- RLS：4テーブルすべて運営のみ（folders と同じ流儀で is_ops() を使う）
-- ============================================================
alter table public.contact_lists           enable row level security;
alter table public.contact_list_imports    enable row level security;
alter table public.contact_list_entries    enable row level security;
alter table public.contact_list_deliveries enable row level security;

drop policy if exists contact_lists_ops on public.contact_lists;
create policy contact_lists_ops on public.contact_lists
  for all to authenticated using (public.is_ops()) with check (public.is_ops());

drop policy if exists contact_list_imports_ops on public.contact_list_imports;
create policy contact_list_imports_ops on public.contact_list_imports
  for all to authenticated using (public.is_ops()) with check (public.is_ops());

drop policy if exists contact_list_entries_ops on public.contact_list_entries;
create policy contact_list_entries_ops on public.contact_list_entries
  for all to authenticated using (public.is_ops()) with check (public.is_ops());

drop policy if exists contact_list_deliveries_ops on public.contact_list_deliveries;
create policy contact_list_deliveries_ops on public.contact_list_deliveries
  for all to authenticated using (public.is_ops()) with check (public.is_ops());

-- ============================================================
-- 件数の再集計（冪等）
--   取込・削除の直後と夜間バッチから呼ぶ。いつ呼んでも実体と一致する。
-- ============================================================
create or replace function public.recount_contact_list(p_list_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update contact_lists c set
    entry_count      = (select count(*) from contact_list_entries e where e.list_id = c.id),
    emailable_count  = (select count(*) from contact_list_entries e where e.list_id = c.id and e.email_norm is not null),
    phone_only_count = (select count(*) from contact_list_entries e where e.list_id = c.id and e.email_norm is null),
    updated_at       = now()
  -- ⚠️ security definer は RLS を迂回するので、運営判定を関数内で必ず掛ける
  where c.id = p_list_id and public.is_ops();
$$;
grant execute on function public.recount_contact_list(bigint) to authenticated;

comment on function public.recount_contact_list(bigint) is
  'リストの件数キャッシュを実体から再集計する（冪等）';

-- ============================================================
-- 並べ替え（手動）
--   受け取った id 配列の順に sort_order を 10 刻みで振り直す。
--   ⚠️ 配列に含まれないリストは触らない（検索で絞った状態からの誤爆を防ぐ）。
-- ============================================================
create or replace function public.reorder_contact_lists(p_ids bigint[])
returns void
language sql
security definer
set search_path = public
as $$
  -- ⚠️ 順序の保証は with ordinality で行う（row_number() over () は順序を保証しない）
  update contact_lists c
     set sort_order = (t.ord * 10)::int,
         updated_at = now()
    from unnest(p_ids) with ordinality as t(id, ord)
   where c.id = t.id and public.is_ops();
$$;
grant execute on function public.reorder_contact_lists(bigint[]) to authenticated;

comment on function public.reorder_contact_lists(bigint[]) is
  'リストの手動並べ替え。渡された順に sort_order を10刻みで振り直す';

-- ============================================================
-- ロールバック（必要時のみ・実行順に注意）
-- ============================================================
-- drop function if exists public.reorder_contact_lists(bigint[]);
-- drop function if exists public.recount_contact_list(bigint);
-- alter table public.scenarios  drop column if exists target_list_ids;
-- alter table public.broadcasts drop column if exists list_dedupe;
-- alter table public.broadcasts drop column if exists target_list_ids;
-- drop table if exists public.contact_list_deliveries;
-- drop table if exists public.contact_list_entries;
-- drop table if exists public.contact_list_imports;
-- drop table if exists public.contact_lists;
