-- ============================================================
-- トークのブックマーク（ナレッジ化）
--   運営がトークの送信履歴をブックマーク → ジャンルだけ選んで登録。
--   想定質問・検索キーワード・成型後案内例は AI が原文から自動生成。
--   AI返信提案（reply-suggest）が ai_enabled のブックマークを優先参照する。
--
--   ⚠️ 参照はサーバー（service role / lib/ai/context.ts）で行う。
-- ============================================================
create table if not exists public.chat_bookmarks (
  id                     bigint generated by default as identity primary key,
  created_at             timestamptz not null default now(),
  -- 登録元トーク
  source_message_id      bigint references public.chat_messages(id) on delete set null,
  source_conversation_id bigint,
  source_member_id       bigint references public.members(id) on delete set null,  -- 登録元メンバ（顧客）
  source_message_at      timestamptz,                                             -- 対象トークの日時
  -- ナレッジ本体
  genre                  text   not null,                       -- ジャンル（アプローチ／クレーム／説明 …）
  original_text          text   not null,                       -- 案内例原文（選択メッセージ）
  expected_question      text,                                  -- 想定される質問（AI生成）
  keywords               text[] not null default '{}',          -- 検索キーワード（AI生成）
  formatted_reply        text,                                  -- 成型後案内例（AI生成）
  ai_enabled             boolean not null default true,         -- AI返信で参照するか
  ai_pending             boolean not null default false,        -- AI自動生成の未完（要確認）
  created_by             bigint references public.members(id) on delete set null,
  is_deleted             boolean not null default false
);

create index if not exists chat_bookmarks_genre_idx     on public.chat_bookmarks(genre)     where is_deleted = false;
create index if not exists chat_bookmarks_enabled_idx    on public.chat_bookmarks(ai_enabled) where is_deleted = false;
create index if not exists chat_bookmarks_message_idx    on public.chat_bookmarks(source_message_id);

comment on table  public.chat_bookmarks is 'トークのブックマーク（AIナレッジ）。ai_enabled のものを reply-suggest が優先参照。';

-- ── RLS：運営（管理者・オペレーター）のみ ──
alter table public.chat_bookmarks enable row level security;
drop policy if exists "chat_bookmarks_ops" on public.chat_bookmarks;
create policy "chat_bookmarks_ops" on public.chat_bookmarks
  for all to authenticated
  using (public.is_ops()) with check (public.is_ops());
