-- ============================================================
-- 権限管理リデザイン（Phase 1）
--   1) role_permissions に新機能キーの既定値を投入（DEFAULT_PERMS 準拠・冪等）
--   2) account_role_access テーブル（Phase 2: LINE/メールのアカウント単位権限）
--
--   ⚠️ role_permissions.feature は自由文字列のためスキーマ変更は不要。
--      新キーは lib/permissions.ts の DEFAULT_PERMS でもフォールバックされるが、
--      DB にも実体を入れておくと管理画面での初期表示が安定する。
--   ⚠️ 既存行は上書きしない（on conflict do nothing）。
--   ⚠️ 派生ロール（ホルダー等）は copy_role_permissions() で別途初期化する。
-- ============================================================

-- ── 2) アカウント単位権限（Phase 2 で enforcement 配線）────────
--   feature      : 対象機能キー（例 'line_chat'（アクセス）/ 'ntf_talk_push_line'（通知））
--   account_type : 'line' | 'mail'
--   account_id   : line_accounts.id / mail_accounts.id
--   role_key     : roles.key
--   access       : アクセス系 'none'|'view'|'operate' / 通知系 'on'|'off'
create table if not exists public.account_role_access (
  feature      text   not null,
  account_type text   not null check (account_type in ('line','mail')),
  account_id   bigint not null,
  role_key     text   not null references public.roles(key) on delete cascade,
  access       text   not null default 'view' check (access in ('none','view','operate','on','off')),
  updated_at   timestamptz not null default now(),
  primary key (feature, account_type, account_id, role_key)
);

alter table public.account_role_access enable row level security;

-- 読み取り: 運営ロールは全て参照可（画面の出し分けに使う）
drop policy if exists "account_role_access_select" on public.account_role_access;
create policy "account_role_access_select" on public.account_role_access
  for select to authenticated
  using (public.is_ops());

-- 書き込み: Phase 1 は管理者のみ（Phase 2 で account_perm/owner へ緩和予定）
drop policy if exists "account_role_access_write" on public.account_role_access;
create policy "account_role_access_write" on public.account_role_access
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- 自動生成: FEATURES × システム固定4ロールの既定値（DEFAULT_PERMS 準拠）
insert into public.role_permissions (role, feature, enabled) values
('管理者','home',true),
('オペレーター','home',true),
('メンバー','home',true),
('外部','home',true),
('管理者','help',true),
('オペレーター','help',true),
('メンバー','help',true),
('外部','help',true),
('管理者','news_view',true),
('オペレーター','news_view',true),
('メンバー','news_view',true),
('外部','news_view',true),
('管理者','notif_center',true),
('オペレーター','notif_center',true),
('メンバー','notif_center',true),
('外部','notif_center',false),
('管理者','global_search',true),
('オペレーター','global_search',true),
('メンバー','global_search',false),
('外部','global_search',false),
('管理者','customers',true),
('オペレーター','customers',true),
('メンバー','customers',false),
('外部','customers',false),
('管理者','member_detail',true),
('オペレーター','member_detail',true),
('メンバー','member_detail',false),
('外部','member_detail',false),
('管理者','member_edit',true),
('オペレーター','member_edit',true),
('メンバー','member_edit',false),
('外部','member_edit',false),
('管理者','unregistered',true),
('オペレーター','unregistered',true),
('メンバー','unregistered',false),
('外部','unregistered',false),
('管理者','member_merge',true),
('オペレーター','member_merge',false),
('メンバー','member_merge',false),
('外部','member_merge',false),
('管理者','member_delete',true),
('オペレーター','member_delete',false),
('メンバー','member_delete',false),
('外部','member_delete',false),
('管理者','member_bulk',true),
('オペレーター','member_bulk',true),
('メンバー','member_bulk',false),
('外部','member_bulk',false),
('管理者','payment_manage',true),
('オペレーター','payment_manage',true),
('メンバー','payment_manage',false),
('外部','payment_manage',false),
('管理者','payment_master',true),
('オペレーター','payment_master',true),
('メンバー','payment_master',false),
('外部','payment_master',false),
('管理者','payment_admin',true),
('オペレーター','payment_admin',false),
('メンバー','payment_admin',false),
('外部','payment_admin',false),
('管理者','refund_manage',true),
('オペレーター','refund_manage',true),
('メンバー','refund_manage',false),
('外部','refund_manage',false),
('管理者','refund_master',true),
('オペレーター','refund_master',true),
('メンバー','refund_master',false),
('外部','refund_master',false),
('管理者','chat',true),
('オペレーター','chat',true),
('メンバー','chat',true),
('外部','chat',false),
('管理者','chat_inbox',true),
('オペレーター','chat_inbox',true),
('メンバー','chat_inbox',false),
('外部','chat_inbox',false),
('管理者','ai',true),
('オペレーター','ai',true),
('メンバー','ai',false),
('外部','ai',false),
('管理者','bookmarks',true),
('オペレーター','bookmarks',true),
('メンバー','bookmarks',false),
('外部','bookmarks',false),
('管理者','summary',true),
('オペレーター','summary',true),
('メンバー','summary',false),
('外部','summary',false),
('管理者','staff_activity',true),
('オペレーター','staff_activity',true),
('メンバー','staff_activity',false),
('外部','staff_activity',false),
('管理者','line_chat',true),
('オペレーター','line_chat',true),
('メンバー','line_chat',false),
('外部','line_chat',false),
('管理者','line_friends',true),
('オペレーター','line_friends',true),
('メンバー','line_friends',false),
('外部','line_friends',false),
('管理者','line_match',true),
('オペレーター','line_match',true),
('メンバー','line_match',false),
('外部','line_match',false),
('管理者','line_richmenu',true),
('オペレーター','line_richmenu',true),
('メンバー','line_richmenu',false),
('外部','line_richmenu',false),
('管理者','line_account',true),
('オペレーター','line_account',true),
('メンバー','line_account',false),
('外部','line_account',false),
('管理者','mailbox',true),
('オペレーター','mailbox',true),
('メンバー','mailbox',false),
('外部','mailbox',false),
('管理者','mailthreads',true),
('オペレーター','mailthreads',true),
('メンバー','mailthreads',false),
('外部','mailthreads',false),
('管理者','mail_send',true),
('オペレーター','mail_send',true),
('メンバー','mail_send',false),
('外部','mail_send',false),
('管理者','mail',true),
('オペレーター','mail',true),
('メンバー','mail',false),
('外部','mail',false),
('管理者','mail_folder',true),
('オペレーター','mail_folder',true),
('メンバー','mail_folder',false),
('外部','mail_folder',false),
('管理者','form',true),
('オペレーター','form',true),
('メンバー','form',false),
('外部','form',false),
('管理者','form_edit',true),
('オペレーター','form_edit',true),
('メンバー','form_edit',false),
('外部','form_edit',false),
('管理者','form_submissions',true),
('オペレーター','form_submissions',true),
('メンバー','form_submissions',false),
('外部','form_submissions',false),
('管理者','form_publish',true),
('オペレーター','form_publish',true),
('メンバー','form_publish',false),
('外部','form_publish',false),
('管理者','form_folder',true),
('オペレーター','form_folder',true),
('メンバー','form_folder',false),
('外部','form_folder',false),
('管理者','broadcast',true),
('オペレーター','broadcast',true),
('メンバー','broadcast',false),
('外部','broadcast',false),
('管理者','ai_draft',true),
('オペレーター','ai_draft',true),
('メンバー','ai_draft',false),
('外部','ai_draft',false),
('管理者','scenario',true),
('オペレーター','scenario',true),
('メンバー','scenario',false),
('外部','scenario',false),
('管理者','broadcast_send',true),
('オペレーター','broadcast_send',false),
('メンバー','broadcast_send',false),
('外部','broadcast_send',false),
('管理者','bc_folder',true),
('オペレーター','bc_folder',true),
('メンバー','bc_folder',false),
('外部','bc_folder',false),
('管理者','calendar',true),
('オペレーター','calendar',true),
('メンバー','calendar',true),
('外部','calendar',true),
('管理者','event_manage',true),
('オペレーター','event_manage',true),
('メンバー','event_manage',false),
('外部','event_manage',false),
('管理者','news_manage',true),
('オペレーター','news_manage',true),
('メンバー','news_manage',false),
('外部','news_manage',false),
('管理者','ai_consult',true),
('オペレーター','ai_consult',false),
('メンバー','ai_consult',true),
('外部','ai_consult',false),
('管理者','comm_content',true),
('オペレーター','comm_content',true),
('メンバー','comm_content',true),
('外部','comm_content',true),
('管理者','content',true),
('オペレーター','content',true),
('メンバー','content',true),
('外部','content',true),
('管理者','content_manage',true),
('オペレーター','content_manage',true),
('メンバー','content_manage',false),
('外部','content_manage',false),
('管理者','ai_html',true),
('オペレーター','ai_html',false),
('メンバー','ai_html',false),
('外部','ai_html',false),
('管理者','content_publish',true),
('オペレーター','content_publish',true),
('メンバー','content_publish',false),
('外部','content_publish',false),
('管理者','content_folder',true),
('オペレーター','content_folder',true),
('メンバー','content_folder',false),
('外部','content_folder',false),
('管理者','ai_data_search',true),
('オペレーター','ai_data_search',true),
('メンバー','ai_data_search',false),
('外部','ai_data_search',false),
('管理者','ai_prompts',true),
('オペレーター','ai_prompts',false),
('メンバー','ai_prompts',false),
('外部','ai_prompts',false),
('管理者','master',true),
('オペレーター','master',true),
('メンバー','master',false),
('外部','master',false),
('管理者','set_permission',true),
('オペレーター','set_permission',false),
('メンバー','set_permission',false),
('外部','set_permission',false),
('管理者','set_role',true),
('オペレーター','set_role',false),
('メンバー','set_role',false),
('外部','set_role',false),
('管理者','set_member',true),
('オペレーター','set_member',true),
('メンバー','set_member',false),
('外部','set_member',false),
('管理者','set_attribute',true),
('オペレーター','set_attribute',true),
('メンバー','set_attribute',false),
('外部','set_attribute',false),
('管理者','set_news',true),
('オペレーター','set_news',true),
('メンバー','set_news',false),
('外部','set_news',false),
('管理者','set_source',true),
('オペレーター','set_source',true),
('メンバー','set_source',false),
('外部','set_source',false),
('管理者','set_welcome',true),
('オペレーター','set_welcome',true),
('メンバー','set_welcome',false),
('外部','set_welcome',false),
('管理者','set_notify',true),
('オペレーター','set_notify',true),
('メンバー','set_notify',false),
('外部','set_notify',false),
('管理者','set_project',true),
('オペレーター','set_project',true),
('メンバー','set_project',false),
('外部','set_project',false),
('管理者','set_anken',true),
('オペレーター','set_anken',true),
('メンバー','set_anken',false),
('外部','set_anken',false),
('管理者','set_template',true),
('オペレーター','set_template',true),
('メンバー','set_template',false),
('外部','set_template',false),
('管理者','folder_perm',true),
('オペレーター','folder_perm',true),
('メンバー','folder_perm',false),
('外部','folder_perm',false),
('管理者','account_perm',true),
('オペレーター','account_perm',false),
('メンバー','account_perm',false),
('外部','account_perm',false),
('管理者','notification',true),
('オペレーター','notification',true),
('メンバー','notification',true),
('外部','notification',true),
('管理者','notify_push_chat',true),
('オペレーター','notify_push_chat',true),
('メンバー','notify_push_chat',true),
('外部','notify_push_chat',false),
('管理者','notify_push_news',true),
('オペレーター','notify_push_news',true),
('メンバー','notify_push_news',true),
('外部','notify_push_news',true),
('管理者','ntf_talk_push_portal',true),
('オペレーター','ntf_talk_push_portal',true),
('メンバー','ntf_talk_push_portal',false),
('外部','ntf_talk_push_portal',false),
('管理者','ntf_talk_push_line',true),
('オペレーター','ntf_talk_push_line',true),
('メンバー','ntf_talk_push_line',false),
('外部','ntf_talk_push_line',false),
('管理者','ntf_talk_push_mail',true),
('オペレーター','ntf_talk_push_mail',true),
('メンバー','ntf_talk_push_mail',false),
('外部','ntf_talk_push_mail',false),
('管理者','ntf_talk_mail_portal',true),
('オペレーター','ntf_talk_mail_portal',true),
('メンバー','ntf_talk_mail_portal',false),
('外部','ntf_talk_mail_portal',false),
('管理者','ntf_talk_mail_line',true),
('オペレーター','ntf_talk_mail_line',true),
('メンバー','ntf_talk_mail_line',false),
('外部','ntf_talk_mail_line',false),
('管理者','ntf_talk_mail_mail',true),
('オペレーター','ntf_talk_mail_mail',true),
('メンバー','ntf_talk_mail_mail',false),
('外部','ntf_talk_mail_mail',false),
('管理者','ntf_form_push',true),
('オペレーター','ntf_form_push',true),
('メンバー','ntf_form_push',false),
('外部','ntf_form_push',false),
('管理者','ntf_form_mail',true),
('オペレーター','ntf_form_mail',true),
('メンバー','ntf_form_mail',false),
('外部','ntf_form_mail',false),
('管理者','chatwork',true),
('オペレーター','chatwork',true),
('メンバー','chatwork',false),
('外部','chatwork',false),
('管理者','dashboard',true),
('オペレーター','dashboard',true),
('メンバー','dashboard',false),
('外部','dashboard',false),
('管理者','kanban',true),
('オペレーター','kanban',true),
('メンバー','kanban',true),
('外部','kanban',false),
('管理者','gantt',true),
('オペレーター','gantt',true),
('メンバー','gantt',true),
('外部','gantt',false),
('管理者','bulk_register',true),
('オペレーター','bulk_register',true),
('メンバー','bulk_register',false),
('外部','bulk_register',false),
('管理者','task_edit',true),
('オペレーター','task_edit',true),
('メンバー','task_edit',true),
('外部','task_edit',false),
('管理者','source_view',true),
('オペレーター','source_view',true),
('メンバー','source_view',false),
('外部','source_view',false),
('管理者','engagement',true),
('オペレーター','engagement',true),
('メンバー','engagement',false),
('外部','engagement',false),
('管理者','content_engage',true),
('オペレーター','content_engage',true),
('メンバー','content_engage',false),
('外部','content_engage',false),
('管理者','notify',true),
('オペレーター','notify',false),
('メンバー','notify',false),
('外部','notify',false)
on conflict (role, feature) do nothing;
-- ============================================================
-- ロールバック: drop table if exists public.account_role_access;
--   （role_permissions の新キー行は残しても無害。消すなら feature 単位で delete）
