-- ============================================================
-- KAWAI AIクローン ナレッジ基盤（フェーズB / 正本スキーマ）
--   出典: docs/database-spec.md（唯一の仕様正本）§8 テーブル / §13 RLS / §14 index
--   ・note / X / chat_bookmark を統合したナレッジ基盤。
--   ・事実(persona_facts) / 意見(persona_positions) / 文体(persona_style) を分離保持。
--   ・埋め込みは OpenAI text-embedding-3-small（1536次元 / pgvector）。
--
--   ⚠️ これは「頭脳」の器（スキーマ）のみ。実データの取込・同期は別途（Mac側フル同期）。
--   ⚠️ 本番適用・feature flag(AI_KAWAI_KNOWLEDGE_ENABLED) 有効化はオーナー承認後。
--   ※ 何度実行しても安全（if not exists / drop policy if exists / on conflict do nothing）。
-- ============================================================

create extension if not exists vector;
create extension if not exists pgcrypto;   -- gen_random_uuid()

-- is_ops() 必須（権限判定を別実装で代替しない：正本§13）
do $$ begin
  if to_regprocedure('public.is_ops()') is null then
    raise exception 'public.is_ops() が存在しません。先に権限基盤を用意してください。';
  end if;
end $$;

-- updated_at 自動更新トリガー関数（無ければ作る：正本§8.1.1）
create or replace function public.set_updated_at() returns trigger
language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

-- ============================================================
-- 8.2 ai_personas
-- ============================================================
create table if not exists public.ai_personas (
  id               uuid primary key default gen_random_uuid(),
  slug             text unique not null,
  display_name     text not null,
  default_language text not null default 'ja',
  system_summary   text,
  is_active        boolean not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- ============================================================
-- 8.3 knowledge_sources
-- ============================================================
create table if not exists public.knowledge_sources (
  id                     bigint generated by default as identity primary key,
  persona_id             uuid not null references public.ai_personas(id) on delete restrict,
  source_type            text not null check (source_type in ('note','x','chat_bookmark')),
  name                   text not null,
  root_locator           text,
  default_retrieval_mode text not null check (default_retrieval_mode in
                          ('answer_and_style','answer_only','style_only','evidence_only','paraphrase_only','excluded')),
  authority_weight       numeric(4,3) not null,
  sync_enabled           boolean not null default true,
  last_synced_at         timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  unique (persona_id, source_type, name)
);

-- ============================================================
-- 8.4 knowledge_sync_runs
-- ============================================================
create table if not exists public.knowledge_sync_runs (
  id              bigint generated by default as identity primary key,
  source_id       bigint not null references public.knowledge_sources(id) on delete restrict,
  mode            text not null check (mode in ('full','incremental','dry_run')),
  status          text not null check (status in ('running','succeeded','partial','failed')),
  started_at      timestamptz not null default now(),
  finished_at     timestamptz,
  scanned_count   integer not null default 0,
  inserted_count  integer not null default 0,
  updated_count   integer not null default 0,
  unchanged_count integer not null default 0,
  excluded_count  integer not null default 0,
  error_count     integer not null default 0,
  manifest_hash   text,
  error_summary   jsonb not null default '[]'::jsonb
);

-- ============================================================
-- 8.5 knowledge_source_items（全ファイル台帳）
-- ============================================================
create table if not exists public.knowledge_source_items (
  id                   bigint generated by default as identity primary key,
  source_id            bigint not null references public.knowledge_sources(id) on delete restrict,
  relative_path        text not null,
  basename             text not null,
  extension            text,
  mime_type            text,
  byte_size            bigint not null,
  content_hash         text not null,
  source_modified_at   timestamptz,
  item_class           text not null check (item_class in ('primary_text','support_text','verification','media','other')),
  ingestion_role       text not null check (ingestion_role in ('canonical','support','evidence','asset','excluded','needs_review')),
  classification_reason text not null,
  is_present           boolean not null default true,
  first_seen_run_id    bigint not null references public.knowledge_sync_runs(id) on delete restrict,
  last_seen_run_id     bigint not null references public.knowledge_sync_runs(id) on delete restrict,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  unique (source_id, relative_path)
);

-- ============================================================
-- 8.6 knowledge_documents
-- ============================================================
create table if not exists public.knowledge_documents (
  id                 bigint generated by default as identity primary key,
  persona_id         uuid not null references public.ai_personas(id) on delete restrict,
  source_id          bigint not null references public.knowledge_sources(id) on delete restrict,
  source_item_id     bigint unique references public.knowledge_source_items(id) on delete set null,
  chat_bookmark_id   bigint unique references public.chat_bookmarks(id) on delete set null,
  external_id        text,
  canonical_url      text,
  source_category    text,
  document_kind      text not null check (document_kind in ('article','post_file','series','bookmark','support','verification')),
  title              text,
  raw_text           text not null,
  normalized_text    text not null,
  language           text not null default 'ja',
  publication_status text not null check (publication_status in ('published','draft','unknown','archived')),
  visibility         text not null check (visibility in ('public','paid','mixed','internal','unknown')),
  authored_at        timestamptz,
  published_at       timestamptz,
  retrieval_mode     text not null,
  is_author_voice    boolean not null,
  is_active          boolean not null default true,
  content_hash       text not null,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create unique index if not exists knowledge_documents_extid_uq
  on public.knowledge_documents(source_id, external_id) where external_id is not null;

-- ============================================================
-- 8.7 knowledge_document_versions
-- ============================================================
create table if not exists public.knowledge_document_versions (
  id                 bigint generated by default as identity primary key,
  document_id        bigint not null references public.knowledge_documents(id) on delete restrict,
  version_no         integer not null,
  raw_text           text not null,
  content_hash       text not null,
  source_modified_at timestamptz,
  sync_run_id        bigint references public.knowledge_sync_runs(id) on delete set null,
  created_at         timestamptz not null default now(),
  unique (document_id, version_no),
  unique (document_id, content_hash)
);

-- ============================================================
-- 8.8 knowledge_units（発言単位）
-- ============================================================
create table if not exists public.knowledge_units (
  id                 bigint generated by default as identity primary key,
  document_id        bigint not null references public.knowledge_documents(id) on delete restrict,
  parent_unit_id     bigint references public.knowledge_units(id) on delete set null,
  unit_kind          text not null check (unit_kind in ('article','post','thread_post','reply','cta','prompt','quote','metadata')),
  ordinal            integer not null default 0,
  title              text,
  body               text not null,
  speaker            text not null check (speaker in ('kawai','external','system','unknown')),
  purpose            text,
  is_author_voice    boolean not null,
  retrieval_mode     text not null,
  answer_weight      numeric(4,3) not null default 1.000,
  style_weight       numeric(4,3) not null default 1.000,
  content_hash       text not null,
  duplicate_group_key text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  unique (document_id, ordinal, unit_kind)
);

-- ============================================================
-- 8.9 knowledge_assets
-- ============================================================
create table if not exists public.knowledge_assets (
  id              bigint generated by default as identity primary key,
  source_item_id  bigint unique references public.knowledge_source_items(id) on delete restrict,
  document_id     bigint references public.knowledge_documents(id) on delete set null,
  unit_id         bigint references public.knowledge_units(id) on delete set null,
  asset_kind      text check (asset_kind in ('image','video','audio','pdf','other')),
  storage_locator text not null,
  width           integer,
  height          integer,
  duration_ms     integer,
  alt_text        text,
  ocr_text        text,
  transcript_text text,
  caption         text,
  rights_scope    text not null default 'unknown' check (rights_scope in ('owned','licensed','external','unknown')),
  is_retrievable  boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- ============================================================
-- 8.10 knowledge_chunks（検索断片）
-- ============================================================
create table if not exists public.knowledge_chunks (
  id              bigint generated by default as identity primary key,
  unit_id         bigint not null references public.knowledge_units(id) on delete restrict,
  ordinal         integer not null,
  heading_path    text[] not null default '{}',
  chunk_kind      text not null check (chunk_kind in
                   ('prose','list','example','instruction','prompt','cta','quote','fact_candidate','position_candidate')),
  text            text not null,
  start_char      integer not null,
  end_char        integer not null,
  token_count     integer not null,
  search_tsv      tsvector generated always as (to_tsvector('simple', coalesce(text,''))) stored,
  embedding       vector(1536),
  embedding_model text,
  is_retrievable  boolean not null default true,
  answer_weight   numeric(4,3) not null default 1.000,
  style_weight    numeric(4,3) not null default 1.000,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (unit_id, ordinal)
);

-- ============================================================
-- 8.11 knowledge_topics / knowledge_unit_topics
-- ============================================================
create table if not exists public.knowledge_topics (
  id          bigint generated by default as identity primary key,
  slug        text unique not null,
  label       text not null,
  parent_id   bigint references public.knowledge_topics(id) on delete set null,
  description text,
  is_active   boolean not null default true
);
create table if not exists public.knowledge_unit_topics (
  unit_id    bigint not null references public.knowledge_units(id) on delete cascade,
  topic_id   bigint not null references public.knowledge_topics(id) on delete cascade,
  source     text not null check (source in ('path','rule','ai','manual')),
  confidence numeric(4,3) not null,
  is_primary boolean not null default false,
  primary key (unit_id, topic_id)
);

-- ============================================================
-- 8.12 persona_facts
-- ============================================================
create table if not exists public.persona_facts (
  id              bigint generated by default as identity primary key,
  persona_id      uuid not null references public.ai_personas(id) on delete restrict,
  fact_type       text not null check (fact_type in
                   ('identity','credential','experience','role','offer','audience','preference','metric','relationship')),
  subject_key     text not null,
  predicate       text not null,
  value_json      jsonb not null,
  valid_from      timestamptz,
  valid_to        timestamptz,
  freshness_class text check (freshness_class in ('stable','periodic','volatile')),
  status          text not null check (status in ('candidate','approved','rejected','superseded')),
  confidence      numeric(4,3) not null,
  source_chunk_id bigint not null references public.knowledge_chunks(id) on delete restrict,
  approved_by     bigint references public.members(id) on delete set null,
  approved_at     timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- ============================================================
-- 8.13 persona_positions
-- ============================================================
create table if not exists public.persona_positions (
  id              bigint generated by default as identity primary key,
  persona_id      uuid not null references public.ai_personas(id) on delete restrict,
  topic_id        bigint references public.knowledge_topics(id) on delete set null,
  position_key    text not null,
  stance          text not null check (stance in ('support','oppose','conditional','neutral')),
  statement       text not null,
  rationale       text,
  conditions      jsonb not null default '[]'::jsonb,
  exceptions      jsonb not null default '[]'::jsonb,
  strength        numeric(4,3) not null,
  valid_from      timestamptz,
  valid_to        timestamptz,
  status          text not null check (status in ('candidate','approved','rejected','superseded')),
  source_chunk_id bigint not null references public.knowledge_chunks(id) on delete restrict,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- ============================================================
-- 8.14 persona_style_profiles / persona_style_examples
-- ============================================================
create table if not exists public.persona_style_profiles (
  id                   bigint generated by default as identity primary key,
  persona_id           uuid not null references public.ai_personas(id) on delete restrict,
  medium               text not null check (medium in ('note','x','chat','common')),
  name                 text not null,
  rules_json           jsonb not null,
  derived_metrics_json jsonb not null default '{}'::jsonb,
  status               text not null check (status in ('draft','approved','archived')),
  version              integer not null,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create table if not exists public.persona_style_examples (
  id               bigint generated by default as identity primary key,
  style_profile_id bigint not null references public.persona_style_profiles(id) on delete cascade,
  unit_id          bigint references public.knowledge_units(id) on delete set null,
  chunk_id         bigint references public.knowledge_chunks(id) on delete set null,
  example_role     text not null check (example_role in ('positive','negative','hook','explanation','cta','reply')),
  purpose          text,
  weight           numeric(4,3) not null,
  is_active        boolean not null default true
);

-- ============================================================
-- 8.15 knowledge_conflicts
-- ============================================================
create table if not exists public.knowledge_conflicts (
  id                bigint generated by default as identity primary key,
  persona_id        uuid not null references public.ai_personas(id) on delete restrict,
  conflict_type     text not null check (conflict_type in ('fact','position','publication','duplicate')),
  subject_key       text not null,
  candidate_refs    jsonb not null,
  resolution_status text not null check (resolution_status in ('open','auto_resolved','manually_resolved','ignored')),
  winning_ref       jsonb,
  resolution_reason text,
  resolved_by       bigint references public.members(id) on delete set null,
  resolved_at       timestamptz,
  created_at        timestamptz not null default now()
);

-- ============================================================
-- 14. インデックス
-- ============================================================
create index if not exists ksi_hash_idx        on public.knowledge_source_items(content_hash);
create index if not exists kdoc_pub_idx         on public.knowledge_documents(persona_id, publication_status, is_active);
create index if not exists kunit_doc_ord_idx    on public.knowledge_units(document_id, ordinal);
create index if not exists kunit_hash_idx        on public.knowledge_units(content_hash);
create index if not exists kunit_dupkey_idx      on public.knowledge_units(duplicate_group_key) where duplicate_group_key is not null;
create index if not exists kchunk_tsv_idx        on public.knowledge_chunks using gin(search_tsv);
-- ベクトル索引は HNSW 非対応の pgvector 環境でも止まらないよう、失敗時はスキップする。
do $$ begin
  begin
    create index if not exists kchunk_vec_idx on public.knowledge_chunks using hnsw (embedding vector_cosine_ops);
  exception when others then
    raise notice 'HNSW索引をスキップしました（pgvectorが未対応の可能性）: %', sqlerrm;
  end;
end $$;
create index if not exists kchunk_retr_idx       on public.knowledge_chunks(unit_id) where is_retrievable = true;
create index if not exists kut_topic_idx         on public.knowledge_unit_topics(topic_id, unit_id);
create index if not exists pfact_idx             on public.persona_facts(persona_id, subject_key, status);
create index if not exists ppos_idx              on public.persona_positions(persona_id, position_key, status);
create index if not exists kconf_idx             on public.knowledge_conflicts(persona_id, resolution_status);

-- ============================================================
-- updated_at トリガー（updated_at を持つ表に付与）
-- ============================================================
do $$
declare t text;
begin
  foreach t in array array[
    'ai_personas','knowledge_sources','knowledge_source_items','knowledge_documents',
    'knowledge_units','knowledge_assets','knowledge_chunks','persona_facts',
    'persona_positions','persona_style_profiles'
  ] loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format('create trigger set_updated_at before update on public.%I
                    for each row execute function public.set_updated_at()', t);
  end loop;
end $$;

-- ============================================================
-- chunk の upsert（埋め込みは text で受けて vector へキャスト）。/api/bot/knowledge/sync から呼ぶ。
-- ============================================================
create or replace function public.knowledge_chunk_upsert(
  p_unit_id bigint,
  p_ordinal integer,
  p_heading text[],
  p_kind    text,
  p_text    text,
  p_start   integer,
  p_end     integer,
  p_tokens  integer,
  p_emb     text,
  p_model   text
)
returns bigint
language sql as $$
  insert into public.knowledge_chunks
    (unit_id, ordinal, heading_path, chunk_kind, text, start_char, end_char, token_count, embedding, embedding_model)
  values
    (p_unit_id, p_ordinal, coalesce(p_heading, '{}'), p_kind, p_text, p_start, p_end, p_tokens,
     nullif(p_emb, '')::vector, p_model)
  on conflict (unit_id, ordinal) do update set
    heading_path    = excluded.heading_path,
    chunk_kind      = excluded.chunk_kind,
    text            = excluded.text,
    start_char      = excluded.start_char,
    end_char        = excluded.end_char,
    token_count     = excluded.token_count,
    embedding       = excluded.embedding,
    embedding_model = excluded.embedding_model,
    updated_at      = now()
  returning id;
$$;

-- ============================================================
-- 公開ボット向けハイブリッド検索（正本 §12 ランキングの中核）
--   ・published かつ visibility=public、回答用途の chunk だけを対象。
--   ・キーワード(ts_rank)＋ベクトル(コサイン)＋媒体権威＋回答重み＋鮮度で採点。
--   ・duplicate_group_key で重複を1件に畳む。
--   ※ conflict penalty・詳細な freshness_class は今後拡張（persona 導入時）。
--   ※ service_role（/api/bot）から呼ぶ。q_emb は text で受けて vector へキャスト。
-- ============================================================
create or replace function public.knowledge_public_search(
  q text, q_emb text, k int default 8
)
returns table (
  chunk_id      bigint,
  document_id   bigint,
  source_type   text,
  title         text,
  canonical_url text,
  chunk_text    text,
  score         real
)
language sql stable as $$
  with qe as (select nullif(q_emb, '')::vector as v),
  base as (
    select c.id as chunk_id, u.document_id, ks.source_type, d.title, d.canonical_url,
           c.text as chunk_text, c.answer_weight, ks.authority_weight,
           u.duplicate_group_key, d.published_at,
           ts_rank(c.search_tsv, plainto_tsquery('simple', q)) as kw,
           case when (select v from qe) is not null and c.embedding is not null
                then 1 - (c.embedding <=> (select v from qe)) else 0 end as vec
    from public.knowledge_chunks c
    join public.knowledge_units u      on u.id = c.unit_id
    join public.knowledge_documents d  on d.id = u.document_id
    join public.knowledge_sources ks   on ks.id = d.source_id
    where c.is_retrievable
      and u.retrieval_mode in ('answer_and_style','answer_only')
      and d.publication_status = 'published'
      and d.visibility = 'public'
      and (
        c.search_tsv @@ plainto_tsquery('simple', q)
        or ((select v from qe) is not null and c.embedding is not null)
      )
  ),
  scored as (
    select *,
      ( vec * 0.45
      + kw  * 0.25
      + authority_weight * 0.15
      + answer_weight    * 0.10
      + (case when published_at is null then 0.5
              else greatest(0, 1 - (extract(epoch from (now() - published_at)) / (86400 * 365 * 2)))
         end)::real * 0.05
      )::real as score
    from base
  ),
  ranked as (
    select *,
      row_number() over (
        partition by coalesce(duplicate_group_key, chunk_id::text)
        order by score desc
      ) as rn
    from scored
  )
  select chunk_id, document_id, source_type, title, canonical_url, chunk_text, score
  from ranked
  where rn = 1
  order by score desc
  limit k;
$$;

-- ============================================================
-- 13. RLS（全表：運営 is_ops() のみ全操作。policy 名 <table>_ops_all）
-- ============================================================
do $$
declare t text;
begin
  foreach t in array array[
    'ai_personas','knowledge_sources','knowledge_sync_runs','knowledge_source_items',
    'knowledge_documents','knowledge_document_versions','knowledge_units','knowledge_assets',
    'knowledge_chunks','knowledge_topics','knowledge_unit_topics','persona_facts',
    'persona_positions','persona_style_profiles','persona_style_examples','knowledge_conflicts'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t || '_ops_all', t);
    execute format('create policy %I on public.%I for all to authenticated
                    using (public.is_ops()) with check (public.is_ops())', t || '_ops_all', t);
  end loop;
end $$;

-- ============================================================
-- 初期 seed（正本 §8.3）
-- ============================================================
insert into public.ai_personas (slug, display_name, default_language, system_summary, is_active)
values ('kawai', '川合卓也', 'ja',
  'AI、デザイン、業務設計、マーケティングを、非エンジニアが実務で使える判断基準と手順へ落とす。結論先出し、短文、具体、誠実を優先する。',
  true)
on conflict (slug) do nothing;

insert into public.knowledge_sources (persona_id, source_type, name, root_locator, default_retrieval_mode, authority_weight)
select p.id, v.source_type, v.name, v.root_locator, 'answer_and_style', v.aw
from public.ai_personas p,
  (values
    ('note','kawai-note','/Users/kawai/Documents/project/kawai/channel/note/articles', 0.850::numeric),
    ('x','kawai-x','/Users/kawai/Documents/project/kawai/channel/x/post', 0.750::numeric),
    ('chat_bookmark','kawai-chat-bookmarks','postgresql://public.chat_bookmarks', 1.000::numeric)
  ) as v(source_type, name, root_locator, aw)
where p.slug = 'kawai'
on conflict (persona_id, source_type, name) do nothing;

-- 文体プロファイル seed（正本 §8.14 初期 rules_json）
insert into public.persona_style_profiles (persona_id, medium, name, rules_json, status, version)
select p.id, v.medium, v.medium || '_default', v.rules::jsonb, 'approved', 1
from public.ai_personas p,
  (values
    ('common', '{"conclusion_first":true,"sentence_length":"short","ending":"assertive","prefer":["判断基準","手順","具体例","成果物","比較"],"avoid":["煽り","誇大表現","根拠のない断定","抽象論だけの回答"]}'),
    ('note',   '{"opening":["結論","失敗原因"],"structure":["H2","H3","箇条書き"],"preferred_formats":["テンプレ","チェックリスト","比較","具体例"],"cta_count_max":1}'),
    ('x',      '{"one_post_one_point":true,"topic_in_first_line":true,"preserve_line_breaks":true,"symbols":["→","✅"],"symbols_only_when_structurally_useful":true,"url_placement":"reply_preferred"}'),
    ('chat',   '{"answer_within_first_sentences":2,"detail_order":["理由","手順","注意点"],"x_style_linebreaks":false,"sales_cta":false,"guess_personal_facts":false}')
  ) as v(medium, rules)
where p.slug = 'kawai'
  and not exists (
    select 1 from public.persona_style_profiles s
    where s.persona_id = p.id and s.medium = v.medium
  );
