-- ============================================================
-- STEP3: 配信停止（unsubscribe / suppression）
--   メール配信の停止アドレスを全社共通で管理する 1 テーブル。
--   一斉配信・シナリオ配信の送信時に照合してスキップする。
--   email は小文字正規化してアプリ側で格納する（unique）。
-- ============================================================
create table if not exists public.email_suppressions (
  id          bigint generated by default as identity primary key,
  email       text not null unique,
  reason      text,
  created_at  timestamptz not null default now()
);

alter table public.email_suppressions enable row level security;

-- 運営（認証済み）が閲覧・管理できる。公開の停止登録はサーバー(service role)経由。
create policy "email_suppressions_auth" on public.email_suppressions
  for all to authenticated using (true) with check (true);

comment on table public.email_suppressions is
  '配信停止リスト（メール）。一斉配信・シナリオ配信の送信時に照合してスキップ。';

-- ロールバック（必要時のみ）
-- drop table if exists public.email_suppressions;
