-- ============================================================
-- メール送信予約（P2）
--   指定日時に自動送信するキュー。Vercel Cron が定期的に処理する。
--   読み書きはサーバー（service role）経由のみ（RLS有効・ポリシー無し）。
-- ============================================================
create table if not exists public.mail_scheduled (
  id            bigint generated by default as identity primary key,
  account_id    bigint not null references public.mail_accounts(id) on delete cascade,
  to_addr       text not null default '',
  cc            text not null default '',
  bcc           text not null default '',
  subject       text not null default '',
  body          text not null default '',
  reply_to_id   bigint,
  attachments   jsonb,                                   -- [{filename, contentBase64, contentType}]
  scheduled_at  timestamptz not null,
  status        text not null default 'pending',         -- pending / sent / canceled / failed
  error         text not null default '',
  created_by    bigint,
  created_at    timestamptz not null default now(),
  sent_at       timestamptz
);

create index if not exists mail_scheduled_due_idx
  on public.mail_scheduled (scheduled_at)
  where status = 'pending';

alter table public.mail_scheduled enable row level security;

comment on table public.mail_scheduled is
  'メール送信予約キュー。cron が scheduled_at 到来分を送信する。サーバー経由でのみ読み書き。';
